### ISSUE TITLE
Missing language support - i18n

### ISSUE THREAD

**Issue by transkamp** [conterra/mapapps-what3words#1]
If a user starts with the english locale support (https://demos.conterra.de/mapapps/resources/apps/downloads_what3words/index.html?lang=en) the user gets a german locale ui.  i18n support ist missing for the intro bundle, and the toggle button.

![image](https://user-images.githubusercontent.com/15154156/189308609-4220a70b-b13c-4d95-a191-91ba38e8168c.png)

**Comment by julkuh** [comment]
Hint:
app.json is not translated and uses hard-coded string values. This is just a problem with this sample app, not with the waht3words bundle itself.

**Comment by transkamp** [comment]
I can't find any i18n resource keys in the bundle. in my opnion they are missing here https://github.com/conterra/mapapps-what3words/tree/main/src/main/js/bundles/dn_what3words

**Comment by njakuschona** [comment]
The commit  6213fe1 adds the i18n files. Thus the tooltip is now shown in the selected language.
As @julkuh mentioned, the app.json is not translated since it only belongs to the sample app and not the bundle itself.

**Comment by sholtkamp** [comment]
Fixed by Nick now merged into main
