### ISSUE TITLE
language of the 3 words depending on the locale set

### ISSUE THREAD

**Issue by transkamp** [conterra/mapapps-what3words#2]
as a user i would aspect that the 3 words for a locale are in the same language than the choosen locale of the app.

- **locale=de ==> geman word**s, 
- **locale=en ==> english words**

actual situation:  in the demo the user gets always the 3 word in german. it doesn't matter which locale locale=de or locale=en the user has choosen.

Demo: 

- https://demos.conterra.de/mapapps/resources/apps/downloads_what3words/index.html?lang=en
- https://demos.conterra.de/mapapps/resources/apps/downloads_what3words/index.html?lang=de

**Comment by sholtkamp** [comment]
Fixed by Nick now merged into main
