### ISSUE TITLE
3 word marker is difficult to see on aerial basemaps

### ISSUE THREAD

**Issue by transkamp** [conterra/mapapps-what3words#3]
as a user the 3 word marker is hard to recognise over aerial basemaps.

suggestion:
the marker itself needs a semi-transparent or full white background and a certain padding so that it can be recognised better on an uneven background map...

![image](https://user-images.githubusercontent.com/15154156/189321682-28b0bcb7-d264-4b00-8dd2-e9e90ad8c427.png)

**Comment by njakuschona** [comment]
I changed the marker. However this is only a property in the app.json and not effects the bundle itself.

**Comment by sholtkamp** [comment]
Fixed by Nick now merged into main
