### ISSUE TITLE
Insuficient contrast of w3w Adresse in der Karte identifizieren - toggle button

### ISSUE THREAD

**Issue by transkamp** [conterra/mapapps-what3words#4]
when the "w3w Adresse in der Karte identifizieren" is active the contrast of this button is insuficient.

suggestion: 
active status: blue background & white text color

![image](https://user-images.githubusercontent.com/15154156/189324301-72d3122b-150e-4238-ac62-cf74bd22c8d5.png)

**Comment by sholtkamp** [comment]
Fixed by Nick now merged into main
