### ISSUE TITLE
Mouse cursor is not changing over the esri popup from crosshair to default

### ISSUE THREAD

**Issue by transkamp** [conterra/mapapps-what3words#6]
as a user, i find it irritating that the mouse cursor (crosshair) does not change to the standard mouse cursor when hovering over the esri popup. 

![image](https://user-images.githubusercontent.com/15154156/189327399-2e826609-f33f-4ea3-bb31-56768cb1ad22.png)
Demo: https://demos.conterra.de/mapapps/resources/apps/downloads_what3words/index.html?lang=en

**Comment by sholtkamp** [comment]
Fixed by Nick now merged into main
